/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class', // Changed from 'media' to 'class' for manual toggling
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        base: {
          white: 'var(--colors-base-white)',
          black: 'var(--colors-base-black)',
          transparent: 'var(--colors-base-transparent)',
        },
        text: {
          primary: 'var(--colors-text-text-primary-900)',
          secondary: 'var(--colors-text-text-secondary-700)',
          tertiary: 'var(--colors-text-text-tertiary-600)',
          quaternary: 'var(--colors-text-text-quaternary-500)',
          disabled: 'var(--colors-text-text-disabled)',
          placeholder: 'var(--colors-text-text-placeholder)',
          white: 'var(--colors-text-text-white)',
          brand: {
            primary: 'var(--colors-text-text-brand-primary-900)',
            secondary: 'var(--colors-text-text-brand-secondary-700)',
            tertiary: 'var(--colors-text-text-brand-tertiary-600)',
          },
          error: {
            primary: 'var(--colors-text-text-error-primary-600)',
          },
          link: {
            button: 'var(--colors-text-text-link-button)',
          }
        },
        bg: {
          primary: 'var(--colors-background-bg-primary)',
          secondary: 'var(--colors-background-bg-secondary)',
          tertiary: 'var(--colors-background-bg-tertiary)',
          quaternary: 'var(--colors-background-bg-quaternary)',
          active: 'var(--colors-background-bg-active)',
          disabled: 'var(--colors-background-bg-disabled)',
          overlay: 'var(--colors-background-bg-overlay)',
          brand: {
            primary: 'var(--colors-background-bg-brand-primary)',
            secondary: 'var(--colors-background-bg-brand-secondary)',
            section: 'var(--colors-background-bg-brand-section)',
            solid: 'var(--colors-background-bg-brand-solid)',
          },
          error: {
            primary: 'var(--colors-background-bg-error-primary)',
            secondary: 'var(--colors-background-bg-error-secondary)',
            solid: 'var(--colors-background-bg-error-solid)',
          },
          success: {
            primary: 'var(--colors-background-bg-success-primary)',
            solid: 'var(--colors-background-bg-success-solid)',
          },
          warning: {
            primary: 'var(--colors-background-bg-warning-primary)',
            solid: 'var(--colors-background-bg-warning-solid)',
          }
        },
        fg: {
          primary: 'var(--colors-foreground-fg-primary-900)',
          secondary: 'var(--colors-foreground-fg-secondary-700)',
          tertiary: 'var(--colors-foreground-fg-tertiary-600)',
          quaternary: 'var(--colors-foreground-fg-quaternary-400)',
          brand: {
            primary: 'var(--colors-foreground-fg-brand-primary-600)',
            secondary: 'var(--colors-foreground-fg-brand-secondary-500)',
          },
          error: {
            primary: 'var(--colors-foreground-fg-error-primary)',
            secondary: 'var(--colors-foreground-fg-error-secondary)',
          },
          success: {
            primary: 'var(--colors-foreground-fg-success-primary)',
            secondary: 'var(--colors-foreground-fg-success-secondary)',
          },
          warning: {
            primary: 'var(--colors-foreground-fg-warning-primary)',
            secondary: 'var(--colors-foreground-fg-warning-secondary)',
          }
        },
        border: {
          primary: 'var(--colors-border-border-primary)',
          secondary: 'var(--colors-border-border-secondary)',
          tertiary: 'var(--colors-border-border-tertiary)',
          disabled: 'var(--colors-border-border-disabled)',
          brand: {
            DEFAULT: 'var(--colors-border-border-brand)',
            solid: 'var(--colors-border-border-brand-alt)', // Check solid vs alt mapping
          },
          error: 'var(--colors-border-border-error)',
        },
        // Primitive Palettes
        gray: {
          25: 'var(--colors-gray-light-mode-25)',
          50: 'var(--colors-gray-light-mode-50)',
          100: 'var(--colors-gray-light-mode-100)',
          200: 'var(--colors-gray-light-mode-200)',
          300: 'var(--colors-gray-light-mode-300)',
          400: 'var(--colors-gray-light-mode-400)',
          500: 'var(--colors-gray-light-mode-500)',
          600: 'var(--colors-gray-light-mode-600)',
          700: 'var(--colors-gray-light-mode-700)',
          800: 'var(--colors-gray-light-mode-800)',
          900: 'var(--colors-gray-light-mode-900)',
          950: 'var(--colors-gray-light-mode-950)',
        },
        brand: {
          25: 'var(--colors-brand-old-25)',
          50: 'var(--colors-brand-old-50)',
          100: 'var(--colors-brand-old-100)',
          200: 'var(--colors-brand-old-200)',
          300: 'var(--colors-brand-old-300)',
          400: 'var(--colors-brand-old-400)',
          500: 'var(--colors-brand-old-500)',
          600: 'var(--colors-brand-old-600)',
          700: 'var(--colors-brand-old-700)',
          800: 'var(--colors-brand-old-800)',
          900: 'var(--colors-brand-old-900)',
          950: 'var(--colors-brand-old-950)',
        },
        error: {
          25: 'var(--colors-error-25)',
          50: 'var(--colors-error-50)',
          100: 'var(--colors-error-100)',
          200: 'var(--colors-error-200)',
          300: 'var(--colors-error-300)',
          400: 'var(--colors-error-400)',
          500: 'var(--colors-error-500)',
          600: 'var(--colors-error-600)',
          700: 'var(--colors-error-700)',
          800: 'var(--colors-error-800)',
          900: 'var(--colors-error-900)',
          950: 'var(--colors-error-950)',
        },
        warning: {
          25: 'var(--colors-warning-25)',
          50: 'var(--colors-warning-50)',
          100: 'var(--colors-warning-100)',
          200: 'var(--colors-warning-200)',
          300: 'var(--colors-warning-300)',
          400: 'var(--colors-warning-400)',
          500: 'var(--colors-warning-500)',
          600: 'var(--colors-warning-600)',
          700: 'var(--colors-warning-700)',
          800: 'var(--colors-warning-800)',
          900: 'var(--colors-warning-900)',
          950: 'var(--colors-warning-950)',
        },
        success: {
          25: 'var(--colors-success-25)',
          50: 'var(--colors-success-50)',
          100: 'var(--colors-success-100)',
          200: 'var(--colors-success-200)',
          300: 'var(--colors-success-300)',
          400: 'var(--colors-success-400)',
          500: 'var(--colors-success-500)',
          600: 'var(--colors-success-600)',
          700: 'var(--colors-success-700)',
          800: 'var(--colors-success-800)',
          900: 'var(--colors-success-900)',
          950: 'var(--colors-success-950)',
        },
        fuchsia: {
          25: 'var(--colors-fuchsia-25)',
          50: 'var(--colors-fuchsia-50)',
          100: 'var(--colors-fuchsia-100)',
          200: 'var(--colors-fuchsia-200)',
          300: 'var(--colors-fuchsia-300)',
          400: 'var(--colors-fuchsia-400)',
          500: 'var(--colors-fuchsia-500)',
          600: 'var(--colors-fuchsia-600)',
          700: 'var(--colors-fuchsia-700)',
          800: 'var(--colors-fuchsia-800)',
          900: 'var(--colors-fuchsia-900)',
          950: 'var(--colors-fuchsia-950)',
        },
        pink: {
          25: 'var(--colors-pink-25)',
          50: 'var(--colors-pink-50)',
          100: 'var(--colors-pink-100)',
          200: 'var(--colors-pink-200)',
          300: 'var(--colors-pink-300)',
          400: 'var(--colors-pink-400)',
          500: 'var(--colors-pink-500)',
          600: 'var(--colors-pink-600)',
          700: 'var(--colors-pink-700)',
          800: 'var(--colors-pink-800)',
          900: 'var(--colors-pink-900)',
          950: 'var(--colors-pink-950)',
        },
        orange: {
          25: 'var(--colors-orange-25)',
          50: 'var(--colors-orange-50)',
          100: 'var(--colors-orange-100)',
          200: 'var(--colors-orange-200)',
          300: 'var(--colors-orange-300)',
          400: 'var(--colors-orange-400)',
          500: 'var(--colors-orange-500)',
          600: 'var(--colors-orange-600)',
          700: 'var(--colors-orange-700)',
          800: 'var(--colors-orange-800)',
          900: 'var(--colors-orange-900)',
          950: 'var(--colors-orange-950)',
        },
      },
      fontFamily: {
        sans: ['"Inter"', 'system-ui', 'sans-serif'],
        display: ['"Inter"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-2xl': ['var(--font-size-display-2xl)', 'var(--line-height-display-2xl)'],
        'display-xl': ['var(--font-size-display-xl)', 'var(--line-height-display-xl)'],
        'display-lg': ['var(--font-size-display-lg)', 'var(--line-height-display-lg)'],
        'display-md': ['var(--font-size-display-md)', 'var(--line-height-display-md)'],
        'display-sm': ['var(--font-size-display-sm)', 'var(--line-height-display-sm)'],
        'display-xs': ['var(--font-size-display-xs)', 'var(--line-height-display-xs)'],
        'text-xl': ['var(--font-size-text-xl)', 'var(--line-height-text-xl)'],
        'text-lg': ['var(--font-size-text-lg)', 'var(--line-height-text-lg)'],
        'text-md': ['var(--font-size-text-md)', 'var(--line-height-text-md)'],
        'text-sm': ['var(--font-size-text-sm)', 'var(--line-height-text-sm)'],
        'text-xs': ['var(--font-size-text-xs)', 'var(--line-height-text-xs)'],
      },
      spacing: {
        'xxs': 'var(--spacing-xxs)',
        'xs': 'var(--spacing-xs)',
        'sm': 'var(--spacing-sm)',
        'md': 'var(--spacing-md)',
        'lg': 'var(--spacing-lg)',
        'xl': 'var(--spacing-xl)',
        '2xl': 'var(--spacing-2xl)',
        '3xl': 'var(--spacing-3xl)',
        '4xl': 'var(--spacing-4xl)',
        '5xl': 'var(--spacing-5xl)',
        '6xl': 'var(--spacing-6xl)',
        '7xl': 'var(--spacing-7xl)',
        '8xl': 'var(--spacing-8xl)',
        '9xl': 'var(--spacing-9xl)',
        '10xl': 'var(--spacing-10xl)',
        '11xl': 'var(--spacing-11xl)',
        '128': 'var(--spacing-32)',
      },
      borderRadius: {
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        '4xl': 'var(--radius-4xl)',
        'full': 'var(--radius-full)',
      }
    },
  },
  plugins: [],
}
